In [2]:
import pandas as pd
import numpy as np

In [111]:
data_train=pd.read_csv('Titanic_data/train.csv')

# 所有特征如下：
# passengerId 乘客编号
# survived 是否存活 1是 0否
# pclass 船舱等级  1=lst 2=2nd 3=3rd
# name 姓名
# sex 性别
# age 年纪
# sibsp 🚢上的兄弟姐妹/配偶个数
# parch 🚢上的父母，孩子
# ticket 船票号码
# fare 船票价格
# cabin 船仓号
# embarked 登船港口  C = Cherbourg, Q = Queenstown, S = Southampton

# Cabin船舱号有大量空值，对于空值填充可能有较大误差，所以我们先不考虑cabin作为特征
# age，由于age缺失很少，我们使用年龄的平均值进行填充
# passengerId是一个连续的序列，与结果无关，我们不选择这个作为特征
# ticket是船票序列，我们不分析
# embarked和sex这两个特征是字符串，进行处理
# 将sex中male=1，famle=0
# embarked中 c=1，q=2，s=3

# 我们选取其中可以转化为数字特征的特征
feature=["Pclass","Age","SibSp","Parch","Fare","Sex","Embarked",]



In [112]:
# 下面处理一些缺失值，进行填充.然后将一些特征转化为数字

#使用平均值填充Age
data_train['Age']=data_train['Age'].fillna(data_train['Age'].median())

## embarked中有两条缺失的，我们使用其中出现最多的来填充
ans=data_train['Embarked'].value_counts()

# 返回最大值索引
fillstr=ans.idxmax()
# 填充
data_train['Embarked']=data_train['Embarked'].fillna(fillstr)

# 我们发现embarked和sex这两个特征是字符串，进行处理
# 我们将sex中male=1，famle=0
# 将embarked中 c=1，q=2，s=3

# data_train['Sex'][data_train['Sex']=='male']=1
# data_train['Sex'][data_train['Sex']=='female']=0

# 使用loc定位行列
# data_train["Sex"] == "male"定位行 sex是列
data_train.loc[data_train["Sex"] == "male","Sex"] = 0
data_train.loc[data_train["Sex"] == "female","Sex"] = 1
data_train.loc[data_train['Embarked']=='C','Embarked']=0
data_train.loc[data_train['Embarked']=='Q','Embarked']=1
data_train.loc[data_train['Embarked']=='S','Embarked']=2

train=data_train[feature]
label=data_train['Survived']
train.info()





<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 7 columns):
Pclass      891 non-null int64
Age         891 non-null float64
SibSp       891 non-null int64
Parch       891 non-null int64
Fare        891 non-null float64
Sex         891 non-null int64
Embarked    891 non-null int64
dtypes: float64(2), int64(5)
memory usage: 48.8 KB


In [8]:
x=np.array([1,2,3,4])

In [9]:
x

array([1, 2, 3, 4])

In [15]:
x.reshape(1,-1)

array([[1, 2, 3, 4]])

In [16]:
b=np.array([4,3,2,1])
b

array([4, 3, 2, 1])

In [18]:
b*x

array([4, 6, 6, 4])

In [19]:
b@x

20

In [25]:
b=b.reshape(-1,1)
b

array([[4],
       [3],
       [2],
       [1]])

In [21]:
x*b

array([4, 6, 6, 4])

In [27]:
x

array([1, 2, 3, 4])

In [26]:
b

array([[4],
       [3],
       [2],
       [1]])

In [28]:
x*b

array([[ 4,  8, 12, 16],
       [ 3,  6,  9, 12],
       [ 2,  4,  6,  8],
       [ 1,  2,  3,  4]])

In [29]:
x@b

array([20])

In [30]:
b*x

array([[ 4,  8, 12, 16],
       [ 3,  6,  9, 12],
       [ 2,  4,  6,  8],
       [ 1,  2,  3,  4]])

In [31]:
b@x

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 1)

In [32]:
x=np.mat([1,2,3])

In [33]:
x

matrix([[1, 2, 3]])

In [55]:
train=np.mat(train)
train[0:10]

matrix([[ 3.    , 22.    ,  1.    ,  0.    ,  7.25  ,  0.    ,  2.    ],
        [ 1.    , 38.    ,  1.    ,  0.    , 71.2833,  1.    ,  0.    ],
        [ 3.    , 26.    ,  0.    ,  0.    ,  7.925 ,  1.    ,  2.    ],
        [ 1.    , 35.    ,  1.    ,  0.    , 53.1   ,  1.    ,  2.    ],
        [ 3.    , 35.    ,  0.    ,  0.    ,  8.05  ,  0.    ,  2.    ],
        [ 3.    , 28.    ,  0.    ,  0.    ,  8.4583,  0.    ,  1.    ],
        [ 1.    , 54.    ,  0.    ,  0.    , 51.8625,  0.    ,  2.    ],
        [ 3.    ,  2.    ,  3.    ,  1.    , 21.075 ,  0.    ,  2.    ],
        [ 3.    , 27.    ,  0.    ,  2.    , 11.1333,  1.    ,  2.    ],
        [ 2.    , 14.    ,  1.    ,  0.    , 30.0708,  1.    ,  0.    ]])

In [56]:
train.mean(axis=0)

matrix([[ 2.30864198, 29.36158249,  0.52300786,  0.38159371, 32.20420797,
          0.35241302,  1.53647587]])

In [45]:
b

array([[4],
       [3],
       [2],
       [1]])

In [46]:
x

matrix([[1, 2, 3]])

In [47]:
b=np.mat(b)

In [48]:
b

matrix([[4],
        [3],
        [2],
        [1]])

In [49]:
b.mean()

2.5

In [53]:
x.mean(axis=0)

matrix([[1., 2., 3.]])

In [57]:
b=np.mat([1,2,3])

In [58]:
b

matrix([[1, 2, 3]])

In [59]:
x

matrix([[1, 2, 3]])

In [60]:
b.T*x

matrix([[1, 2, 3],
        [2, 4, 6],
        [3, 6, 9]])

In [67]:
a=b.T@x

In [68]:
a

matrix([[1, 2, 3],
        [2, 4, 6],
        [3, 6, 9]])

In [69]:
a.std()

2.4037008503093262

In [72]:
a.mean(axis=0)

matrix([[2., 4., 6.]])

In [71]:
a.std(axis=1)

matrix([[0.81649658],
        [1.63299316],
        [2.44948974]])

In [65]:
x*b.T

matrix([[14]])

In [66]:
x@b.T

matrix([[14]])

In [73]:
a=np.mat([[1,2,3],[1,2,4],[9,10,11]])

In [74]:
a

matrix([[ 1,  2,  3],
        [ 1,  2,  4],
        [ 9, 10, 11]])

In [75]:
a.mean(axis=1)

matrix([[ 2.        ],
        [ 2.33333333],
        [10.        ]])

In [76]:
a.mean(axis=0)

matrix([[3.66666667, 4.66666667, 6.        ]])

In [143]:

def loadData(fileName):
    data_train = pd.read_csv(fileName)



    # titanic训练集所有特征如下：
    # passengerId 乘客编号
    # survived 是否存活 1是 0否
    # pclass 船舱等级  1=lst 2=2nd 3=3rd
    # name 姓名
    # sex 性别
    # age 年纪
    # sibsp 🚢上的兄弟姐妹/配偶个数
    # parch 🚢上的父母，孩子
    # ticket 船票号码
    # fare 船票价格
    # cabin 船仓号
    # embarked 登船港口  C = Cherbourg, Q = Queenstown, S = Southampton

    # Cabin船舱号有大量空值，对于空值填充可能有较大误差，所以我们先不考虑cabin作为特征
    # age，由于age缺失很少，我们使用年龄的平均值进行填充
    # passengerId是一个连续的序列，与结果无关，我们不选择这个作为特征
    # ticket是船票序列，我们不分析
    # embarked和sex这两个特征是字符串，进行处理
    # 将sex中male=1，famle=0
    # embarked中 c=1，q=2，s=3

    # 我们选取其中可以转化为数字特征的特征
    feature = ["Pclass", "Age", "SibSp", "Parch", "Fare", "Sex", "Embarked", ]

    # 下面处理一些缺失值，进行填充.然后将一些特征转化为数字

    # 使用平均值填充Age
    data_train['Age'] = data_train['Age'].fillna(data_train['Age'].median())

    ## embarked中有两条缺失的，我们使用其中出现最多的来填充
    ans = data_train['Embarked'].value_counts()

    # 返回最大值索引
    fillstr = ans.idxmax()
    # 填充
    data_train['Embarked'] = data_train['Embarked'].fillna(fillstr)

    # 我们发现embarked和sex这两个特征是字符串，进行处理
    # 我们将sex中male=1，famle=0
    # 将embarked中 c=1，q=2，s=3

    # data_train['Sex'][data_train['Sex']=='male']=1
    # data_train['Sex'][data_train['Sex']=='female']=0

    # 使用loc定位行列
    # data_train["Sex"] == "male"定位行 sex是列
    data_train.loc[data_train["Sex"] == "male", "Sex"] = 0
    data_train.loc[data_train["Sex"] == "female", "Sex"] = 1
    data_train.loc[data_train['Embarked'] == 'C', 'Embarked'] = 0
    data_train.loc[data_train['Embarked'] == 'Q', 'Embarked'] = 1
    data_train.loc[data_train['Embarked'] == 'S', 'Embarked'] = 2

    #选取出我们需要的特征作为训练集
    x_train = data_train[feature]
    #将dataframe转为矩阵
    x_train=np.mat(x_train)

    # 分类结果label
    y_label = data_train['Survived']
    
    y_label.loc[y_label==0]=-1

    # 将dataframe转为列向量 891x1
    y_label=np.mat(y_label).T
    return x_train,y_label

In [145]:
x,y=loadData('Titanic_data/train.csv')

In [146]:
x.shape[1]

7

In [147]:
y

matrix([[-1],
        [ 1],
        [ 1],
        [ 1],
        [-1],
        [-1],
        [-1],
        [-1],
        [ 1],
        [ 1],
        [ 1],
        [ 1],
        [-1],
        [-1],
        [-1],
        [ 1],
        [-1],
        [ 1],
        [-1],
        [ 1],
        [-1],
        [ 1],
        [ 1],
        [ 1],
        [-1],
        [ 1],
        [-1],
        [-1],
        [ 1],
        [-1],
        [-1],
        [ 1],
        [ 1],
        [-1],
        [-1],
        [-1],
        [ 1],
        [-1],
        [-1],
        [ 1],
        [-1],
        [-1],
        [-1],
        [ 1],
        [ 1],
        [-1],
        [-1],
        [ 1],
        [-1],
        [-1],
        [-1],
        [-1],
        [ 1],
        [ 1],
        [-1],
        [ 1],
        [ 1],
        [-1],
        [ 1],
        [-1],
        [-1],
        [ 1],
        [-1],
        [-1],
        [-1],
        [ 1],
        [ 1],
        [-1],
        [ 1],
        [-1],
        [-1],
      

In [148]:
#数据归一化
def norm(x_data):

    #均值
    mu=np.zeros((1,x_data.shape[1]))

    # 标准差
    sigma=np.zeros((1,x_data.shape[1]))
    #计算均值与标准差
    # axis=0代表计算每一列的平均值
    # axis=1代表计算每一行的均值
    # 默认计算所有值
    mu=x_data.mean(axis=0)
    sigma=x_data.std(axis=0)
    # 归一化
    x_norm=(x_data-mu)/(sigma)
    return x_norm


In [149]:
np.zeros((1,2))

array([[0., 0.]])

In [150]:
x=norm(x)
x

matrix([[ 0.82737724, -0.56573646,  0.43279337, ..., -0.50244517,
         -0.73769513,  0.58595414],
        [-1.56610693,  0.66386103,  0.43279337, ...,  0.78684529,
          1.35557354, -1.9423032 ],
        [ 0.82737724, -0.25833709, -0.4745452 , ..., -0.48885426,
          1.35557354,  0.58595414],
        ...,
        [ 0.82737724, -0.1046374 ,  0.43279337, ..., -0.17626324,
          1.35557354,  0.58595414],
        [-1.56610693, -0.25833709, -0.4745452 , ..., -0.04438104,
         -0.73769513, -1.9423032 ],
        [ 0.82737724,  0.20276197, -0.4745452 , ..., -0.49237783,
         -0.73769513, -0.67817453]])

In [181]:
def preceptron(x_data,y_label):
    # y=w*x+b

    # #将data转置
    # x_data=x_data.T

    # 初始化w为全0，长度与每一个样本特征一致
    w=np.zeros((x_data.shape[1],1)) #7x1的列向量
    #初始b=0
    b=0
    #学习率  也就是我们梯度下降的步长
    alpha=0.001
    #迭代次数

    iters=1000

    m,n=x_data.shape #返回x_data的维度
    
    
    for iter in range(iters):
        #计算每个循环错误样本数，计算正确率
        count = 0
        
        for i,x in enumerate(x_data):
            #计算需要把握好每一个向量的维度，才不容易出错
            # x_data是891x7，x是1x7，y_label是891x1

            y=y_label[i]

            if y*(x@w+b)<=0:
                #这些点被归于误差点

                #x是1x7行向量，w是7x1的列向量
                # 所以梯度下降更新w时候，x需要转置
                # y是1x1的矩阵,x.T是7x1的矩阵,取其中的值相乘用np.multiply()
                w+=alpha*np.multiply(y,x.T)
                b+=alpha*y
                # 误分类样本加一
                count+=1
        #计算分类正确率
        print(count,m)
        acc=(m-count)/m
        print('Round %d'%(iter),end=' ')
        print('acc=',acc)
        print(w,b)
                    
    # 返回训练完毕的w，b
    return w,b

In [182]:
w,b=preceptron(x,y)

232 891
Round 0 acc= 0.7396184062850729
[[-0.00045801]
 [-0.00190333]
 [-0.00268026]
 [-0.00153526]
 [ 0.00514634]
 [ 0.00147539]
 [-0.00243604]] [[-0.002]]
252 891
Round 1 acc= 0.7171717171717171
[[-0.00165475]
 [-0.00271025]
 [-0.00540228]
 [-0.00029396]
 [ 0.00533435]
 [ 0.00147539]
 [-0.00243604]] [[-0.002]]
252 891
Round 2 acc= 0.7171717171717171
[[-0.0028515 ]
 [-0.00269719]
 [-0.00540228]
 [-0.00401787]
 [ 0.00602337]
 [ 0.00147539]
 [-0.00117191]] [[-0.002]]
256 891
Round 3 acc= 0.712682379349046
[[-0.0028515 ]
 [-0.00278633]
 [-0.00449494]
 [-0.00277656]
 [ 0.00567345]
 [ 0.00147539]
 [-0.00117191]] [[-0.002]]
252 891
Round 4 acc= 0.7171717171717171
[[-0.00165475]
 [-0.00164588]
 [-0.00540228]
 [-0.00401787]
 [ 0.00609276]
 [ 0.00147539]
 [-0.00117191]] [[-0.002]]
239 891
Round 5 acc= 0.7317620650953984
[[-0.00248213]
 [-0.00147054]
 [-0.00492773]
 [-0.00354419]
 [ 0.00441151]
 [ 0.00221309]
 [-0.00175786]] [[-0.003]]
249 891
Round 6 acc= 0.7205387205387206
[[-0.0028515 ]
 [-0

239 891
Round 54 acc= 0.7317620650953984
[[-0.0028515 ]
 [-0.00123012]
 [-0.0035876 ]
 [-0.00401787]
 [ 0.0055048 ]
 [ 0.00147539]
 [-0.00117191]] [[-0.002]]
242 891
Round 55 acc= 0.7283950617283951
[[-0.0028515 ]
 [-0.00137076]
 [-0.0035876 ]
 [-0.00401787]
 [ 0.00576613]
 [ 0.00147539]
 [-0.00117191]] [[-0.002]]
242 891
Round 56 acc= 0.7283950617283951
[[-0.00165475]
 [-0.00300382]
 [-0.00449494]
 [-0.00153526]
 [ 0.00595909]
 [ 0.00147539]
 [-0.00243604]] [[-0.002]]
254 891
Round 57 acc= 0.7149270482603816
[[-0.0028515 ]
 [-0.00257423]
 [-0.00540228]
 [-0.00029396]
 [ 0.00584021]
 [ 0.00147539]
 [-0.00243604]] [[-0.002]]
246 891
Round 58 acc= 0.7239057239057239
[[-0.00045801]
 [-0.00203628]
 [-0.00449494]
 [-0.00401787]
 [ 0.00645549]
 [ 0.00147539]
 [-0.00117191]] [[-0.002]]
247 891
Round 59 acc= 0.7227833894500562
[[-0.00202412]
 [-0.00255052]
 [-0.00587682]
 [-0.00076763]
 [ 0.00706372]
 [ 0.00283096]
 [-0.00185008]] [[-0.001]]
256 891
Round 60 acc= 0.712682379349046
[[-0.0012853

244 891
Round 106 acc= 0.7261503928170595
[[-0.00045801]
 [-0.00192715]
 [-0.00449494]
 [-0.00401787]
 [ 0.00521115]
 [ 0.00147539]
 [-0.00117191]] [[-0.002]]
243 891
Round 107 acc= 0.7272727272727273
[[-0.00248213]
 [-0.00189245]
 [-0.00583507]
 [-0.00354419]
 [ 0.00543842]
 [ 0.00221309]
 [-0.00049373]] [[-0.003]]
232 891
Round 108 acc= 0.7396184062850729
[[-0.00248213]
 [-0.00343559]
 [-0.00492773]
 [-0.00106159]
 [ 0.00588407]
 [ 0.00221309]
 [-0.00302199]] [[-0.003]]
240 891
Round 109 acc= 0.7306397306397306
[[-0.00202412]
 [-0.00274111]
 [-0.00496949]
 [-0.00076763]
 [ 0.00448076]
 [ 0.00283096]
 [-0.00058595]] [[-0.001]]
248 891
Round 110 acc= 0.7216610549943884
[[-0.00128539]
 [-0.00340869]
 [-0.00583507]
 [-0.00106159]
 [ 0.00570109]
 [ 0.00221309]
 [-0.00175786]] [[-0.003]]
251 891
Round 111 acc= 0.7182940516273849
[[-2.85149657e-03]
 [-2.96231823e-03]
 [-2.68026386e-03]
 [-2.77656325e-03]
 [ 6.19648654e-03]
 [ 1.47539026e-03]
 [ 9.22203856e-05]] [[-0.002]]
254 891
Round 112 

253 891
Round 160 acc= 0.7160493827160493
[[-0.00082738]
 [-0.00219778]
 [-0.00406215]
 [-0.00076763]
 [ 0.0048785 ]
 [ 0.0007377 ]
 [-0.00058595]] [[-0.001]]
242 891
Round 161 acc= 0.7283950617283951
[[-0.00248213]
 [-0.00140522]
 [-0.00583507]
 [-0.00354419]
 [ 0.00510376]
 [ 0.00221309]
 [-0.00175786]] [[-0.003]]
249 891
Round 162 acc= 0.7205387205387206
[[-0.00165475]
 [-0.00384071]
 [-0.00268026]
 [-0.00153526]
 [ 0.00570864]
 [ 0.00147539]
 [-0.00243604]] [[-0.002]]
244 891
Round 163 acc= 0.7261503928170595
[[-0.00165475]
 [-0.00249507]
 [-0.00268026]
 [-0.00277656]
 [ 0.00637292]
 [ 0.00147539]
 [-0.00117191]] [[-0.002]]
243 891
Round 164 acc= 0.7272727272727273
[[-0.00082738]
 [-0.00266349]
 [-0.00496949]
 [-0.00200893]
 [ 0.00539085]
 [ 0.00283096]
 [-0.00185008]] [[-0.001]]
249 891
Round 165 acc= 0.7205387205387206
[[-0.0028515 ]
 [-0.00252658]
 [-0.00449494]
 [-0.00029396]
 [ 0.00609858]
 [ 0.00147539]
 [-0.00243604]] [[-0.002]]
247 891
Round 166 acc= 0.7227833894500562
[[-0

244 891
Round 214 acc= 0.7261503928170595
[[-0.00165475]
 [-0.00061148]
 [-0.00449494]
 [-0.00401787]
 [ 0.00610225]
 [ 0.00147539]
 [-0.00117191]] [[-0.002]]
251 891
Round 215 acc= 0.7182940516273849
[[-0.00202412]
 [-0.00196493]
 [-0.00496949]
 [-0.00076763]
 [ 0.00493687]
 [ 0.00283096]
 [-0.00185008]] [[-0.001]]
247 891
Round 216 acc= 0.7227833894500562
[[-0.00165475]
 [-0.00137383]
 [-0.00268026]
 [-0.00029396]
 [ 0.00400849]
 [ 0.00147539]
 [-0.00243604]] [[-0.002]]
246 891
Round 217 acc= 0.7239057239057239
[[-0.00165475]
 [-0.00257115]
 [-0.00540228]
 [-0.00401787]
 [ 0.00500223]
 [ 0.00147539]
 [-0.00117191]] [[-0.002]]
234 891
Round 218 acc= 0.7373737373737373
[[-1.65475449e-03]
 [-2.28219712e-03]
 [-4.49494098e-03]
 [-4.01786673e-03]
 [ 5.54544553e-03]
 [ 1.47539026e-03]
 [ 9.22203856e-05]] [[-0.002]]
251 891
Round 219 acc= 0.7182940516273849
[[-0.00202412]
 [-0.00261738]
 [-0.00315481]
 [-0.00076763]
 [ 0.00644328]
 [ 0.0007377 ]
 [-0.00058595]] [[-0.001]]
246 891
Round 220 

247 891
Round 274 acc= 0.7227833894500562
[[-0.0028515 ]
 [-0.00224608]
 [-0.00449494]
 [-0.00029396]
 [ 0.00567267]
 [ 0.00147539]
 [-0.00243604]] [[-0.002]]
249 891
Round 275 acc= 0.7205387205387206
[[-0.00128539]
 [-0.00134681]
 [-0.00583507]
 [-0.00106159]
 [ 0.00468432]
 [ 0.00221309]
 [-0.00302199]] [[-0.003]]
244 891
Round 276 acc= 0.7261503928170595
[[-0.00082738]
 [-0.00199721]
 [-0.00315481]
 [-0.00076763]
 [ 0.0056996 ]
 [ 0.0007377 ]
 [-0.00311421]] [[-0.001]]
254 891
Round 277 acc= 0.7149270482603816
[[-0.00248213]
 [-0.00101252]
 [-0.0040204 ]
 [-0.00354419]
 [ 0.00322639]
 [ 0.00221309]
 [-0.00049373]] [[-0.003]]
255 891
Round 278 acc= 0.7138047138047138
[[-0.0028515 ]
 [-0.00161668]
 [-0.0035876 ]
 [-0.00277656]
 [ 0.00497249]
 [ 0.00147539]
 [-0.00117191]] [[-0.002]]
248 891
Round 279 acc= 0.7216610549943884
[[-0.00165475]
 [-0.00146913]
 [-0.00177293]
 [-0.00277656]
 [ 0.00335667]
 [ 0.00147539]
 [-0.00117191]] [[-0.002]]
242 891
Round 280 acc= 0.7283950617283951
[[-0

246 891
Round 333 acc= 0.7239057239057239
[[-0.00165475]
 [-0.00296847]
 [-0.00540228]
 [-0.00029396]
 [ 0.0052035 ]
 [ 0.00147539]
 [-0.00117191]] [[-0.002]]
245 891
Round 334 acc= 0.7250280583613917
[[-0.00202412]
 [-0.00341816]
 [-0.00406215]
 [-0.00076763]
 [ 0.00482456]
 [ 0.0007377 ]
 [-0.00058595]] [[-0.001]]
260 891
Round 335 acc= 0.7081930415263749
[[-0.00248213]
 [-0.0030037 ]
 [-0.00583507]
 [-0.00106159]
 [ 0.00645438]
 [ 0.00221309]
 [-0.00302199]] [[-0.003]]
260 891
Round 336 acc= 0.7081930415263749
[[-0.00367887]
 [-0.00132529]
 [-0.00492773]
 [-0.00354419]
 [ 0.00569933]
 [ 0.00221309]
 [-0.00049373]] [[-0.003]]
253 891
Round 337 acc= 0.7160493827160493
[[-0.00165475]
 [-0.00322899]
 [-0.00449494]
 [-0.00029396]
 [ 0.00519881]
 [ 0.00147539]
 [-0.00243604]] [[-0.002]]
241 891
Round 338 acc= 0.7295173961840629
[[-0.00248213]
 [-0.00165729]
 [-0.00220572]
 [-0.00230289]
 [ 0.00433612]
 [ 0.00221309]
 [-0.00175786]] [[-0.003]]
247 891
Round 339 acc= 0.7227833894500562
[[-0

244 891
Round 389 acc= 0.7261503928170595
[[-0.00082738]
 [-0.0025828 ]
 [-0.00496949]
 [-0.00076763]
 [ 0.00589573]
 [ 0.0007377 ]
 [-0.00058595]] [[-0.001]]
243 891
Round 390 acc= 0.7272727272727273
[[-0.00165475]
 [-0.00211236]
 [-0.00540228]
 [-0.00153526]
 [ 0.00582945]
 [ 0.00147539]
 [-0.00243604]] [[-0.002]]
249 891
Round 391 acc= 0.7205387205387206
[[-0.00248213]
 [-0.00303828]
 [-0.00492773]
 [-0.00106159]
 [ 0.00515947]
 [ 0.00221309]
 [-0.00302199]] [[-0.003]]
257 891
Round 392 acc= 0.7115600448933782
[[-0.00165475]
 [-0.00216308]
 [-0.00449494]
 [-0.00029396]
 [ 0.00627736]
 [ 0.00147539]
 [-0.00243604]] [[-0.002]]
248 891
Round 393 acc= 0.7216610549943884
[[-0.00165475]
 [-0.00193253]
 [-0.00449494]
 [-0.00029396]
 [ 0.0066158 ]
 [ 0.00147539]
 [-0.00243604]] [[-0.002]]
255 891
Round 394 acc= 0.7138047138047138
[[-0.00248213]
 [-0.00290379]
 [-0.00492773]
 [-0.00230289]
 [ 0.00562534]
 [ 0.00221309]
 [-0.00175786]] [[-0.003]]
244 891
Round 395 acc= 0.7261503928170595
[[-0

256 891
Round 449 acc= 0.712682379349046
[[-0.00248213]
 [-0.00071357]
 [-0.00492773]
 [-0.00230289]
 [ 0.00379114]
 [ 0.00221309]
 [-0.00175786]] [[-0.003]]
243 891
Round 450 acc= 0.7272727272727273
[[-0.0028515 ]
 [-0.00202859]
 [-0.00449494]
 [-0.00277656]
 [ 0.00438201]
 [ 0.00147539]
 [-0.00117191]] [[-0.002]]
260 891
Round 451 acc= 0.7081930415263749
[[-0.0028515 ]
 [-0.00368086]
 [-0.0035876 ]
 [-0.00401787]
 [ 0.00697209]
 [ 0.00147539]
 [-0.00117191]] [[-0.002]]
240 891
Round 452 acc= 0.7306397306397306
[[-0.00165475]
 [-0.00264339]
 [-0.00540228]
 [-0.00029396]
 [ 0.00523421]
 [ 0.00147539]
 [-0.00243604]] [[-0.002]]
252 891
Round 453 acc= 0.7171717171717171
[[-2.85149657e-03]
 [-2.36750044e-03]
 [-2.68026386e-03]
 [-2.77656325e-03]
 [ 5.24964281e-03]
 [ 1.47539026e-03]
 [ 9.22203856e-05]] [[-0.002]]
245 891
Round 454 acc= 0.7250280583613917
[[-0.00202412]
 [-0.00271498]
 [-0.00496949]
 [-0.00076763]
 [ 0.004606  ]
 [ 0.00283096]
 [-0.00058595]] [[-0.001]]
241 891
Round 455 a

244 891
Round 501 acc= 0.7261503928170595
[[-0.00082738]
 [-0.00254899]
 [-0.00496949]
 [-0.00076763]
 [ 0.00595678]
 [ 0.0007377 ]
 [-0.00058595]] [[-0.001]]
238 891
Round 502 acc= 0.7328843995510662
[[-0.00202412]
 [-0.00240758]
 [-0.00224747]
 [-0.00076763]
 [ 0.00581936]
 [ 0.0007377 ]
 [ 0.00067817]] [[-0.001]]
243 891
Round 503 acc= 0.7272727272727273
[[-0.00165475]
 [-0.00257115]
 [-0.00268026]
 [-0.00277656]
 [ 0.00641401]
 [ 0.00147539]
 [-0.00117191]] [[-0.002]]
242 891
Round 504 acc= 0.7283950617283951
[[-4.58012403e-04]
 [-3.60247743e-03]
 [-4.49494098e-03]
 [-1.53525976e-03]
 [ 5.27950255e-03]
 [ 1.47539026e-03]
 [ 9.22203856e-05]] [[-0.002]]
252 891
Round 505 acc= 0.7171717171717171
[[-0.0028515 ]
 [-0.00308989]
 [-0.00449494]
 [-0.00029396]
 [ 0.00355589]
 [ 0.00147539]
 [-0.00243604]] [[-0.002]]
249 891
Round 506 acc= 0.7205387205387206
[[-0.00248213]
 [-0.00240196]
 [-0.00492773]
 [-0.00106159]
 [ 0.00481246]
 [ 0.00221309]
 [-0.00302199]] [[-0.003]]
255 891
Round 507 

245 891
Round 557 acc= 0.7250280583613917
[[-0.00165475]
 [-0.00303302]
 [-0.00540228]
 [-0.00153526]
 [ 0.00399054]
 [ 0.00147539]
 [-0.00117191]] [[-0.002]]
248 891
Round 558 acc= 0.7216610549943884
[[-0.0028515 ]
 [-0.00450546]
 [-0.0035876 ]
 [-0.00401787]
 [ 0.00732778]
 [ 0.00147539]
 [-0.00117191]] [[-0.002]]
247 891
Round 559 acc= 0.7227833894500562
[[-0.00248213]
 [-0.00294683]
 [-0.00583507]
 [-0.00106159]
 [ 0.00492647]
 [ 0.00011982]
 [-0.00175786]] [[-0.003]]
243 891
Round 560 acc= 0.7272727272727273
[[-0.00165475]
 [-0.0036532 ]
 [-0.00449494]
 [-0.00153526]
 [ 0.00459961]
 [ 0.00147539]
 [-0.00243604]] [[-0.002]]
253 891
Round 561 acc= 0.7160493827160493
[[-0.00082738]
 [-0.00222007]
 [-0.00406215]
 [-0.00076763]
 [ 0.00488427]
 [ 0.0007377 ]
 [-0.00058595]] [[-0.001]]
246 891
Round 562 acc= 0.7239057239057239
[[-0.00248213]
 [-0.00245883]
 [-0.0040204 ]
 [-0.00354419]
 [ 0.00474601]
 [ 0.00221309]
 [-0.00049373]] [[-0.003]]
236 891
Round 563 acc= 0.7351290684624018
[[-0

260 891
Round 615 acc= 0.7081930415263749
[[-0.00367887]
 [-0.00211839]
 [-0.0040204 ]
 [-0.00354419]
 [ 0.00584234]
 [ 0.00221309]
 [-0.00175786]] [[-0.003]]
251 891
Round 616 acc= 0.7182940516273849
[[-0.00165475]
 [-0.00219075]
 [-0.00449494]
 [-0.00401787]
 [ 0.00474114]
 [ 0.00147539]
 [-0.00117191]] [[-0.002]]
234 891
Round 617 acc= 0.7373737373737373
[[-0.00165475]
 [-0.00278633]
 [-0.00449494]
 [-0.00153526]
 [ 0.00505977]
 [ 0.00147539]
 [-0.00243604]] [[-0.002]]
253 891
Round 618 acc= 0.7160493827160493
[[-0.00248213]
 [-0.00199619]
 [-0.0040204 ]
 [-0.00354419]
 [ 0.0054925 ]
 [ 0.00011982]
 [-0.00175786]] [[-0.003]]
251 891
Round 619 acc= 0.7182940516273849
[[-0.0028515 ]
 [-0.00226683]
 [-0.00540228]
 [-0.00029396]
 [ 0.00518108]
 [ 0.00356866]
 [-0.00117191]] [[-0.002]]
237 891
Round 620 acc= 0.734006734006734
[[-0.00248213]
 [-0.00202079]
 [-0.00583507]
 [-0.00106159]
 [ 0.00532983]
 [ 0.00221309]
 [-0.00175786]] [[-0.003]]
242 891
Round 621 acc= 0.7283950617283951
[[-0.

248 891
Round 674 acc= 0.7216610549943884
[[-0.0028515 ]
 [-0.00257038]
 [-0.00449494]
 [-0.00277656]
 [ 0.00499731]
 [ 0.00147539]
 [-0.00117191]] [[-0.002]]
240 891
Round 675 acc= 0.7306397306397306
[[-0.00165475]
 [-0.00276251]
 [-0.00449494]
 [-0.00153526]
 [ 0.0049729 ]
 [ 0.00147539]
 [-0.00243604]] [[-0.002]]
252 891
Round 676 acc= 0.7171717171717171
[[-2.85149657e-03]
 [-3.10141645e-03]
 [-3.58760242e-03]
 [-2.77656325e-03]
 [ 5.88181159e-03]
 [ 1.47539026e-03]
 [ 9.22203856e-05]] [[-0.002]]
246 891
Round 677 acc= 0.7239057239057239
[[-0.00165475]
 [-0.00146759]
 [-0.00449494]
 [-0.00277656]
 [ 0.00481459]
 [ 0.00147539]
 [-0.00117191]] [[-0.002]]
246 891
Round 678 acc= 0.7239057239057239
[[-0.0028515 ]
 [-0.00265261]
 [-0.00540228]
 [-0.00401787]
 [ 0.00609993]
 [ 0.00147539]
 [-0.00117191]] [[-0.002]]
256 891
Round 679 acc= 0.712682379349046
[[-0.0028515 ]
 [-0.00274176]
 [-0.00449494]
 [-0.00277656]
 [ 0.00575001]
 [ 0.00147539]
 [-0.00117191]] [[-0.002]]
248 891
Round 680 a

239 891
Round 729 acc= 0.7317620650953984
[[-4.58012403e-04]
 [-2.47816422e-03]
 [-5.40227954e-03]
 [-1.53525976e-03]
 [ 3.50918032e-03]
 [ 1.47539026e-03]
 [ 9.22203856e-05]] [[-0.002]]
238 891
Round 730 acc= 0.7328843995510662
[[-4.58012403e-04]
 [-2.39439789e-03]
 [-5.40227954e-03]
 [-1.53525976e-03]
 [ 3.30757975e-03]
 [ 1.47539026e-03]
 [ 9.22203856e-05]] [[-0.002]]
249 891
Round 731 acc= 0.7205387205387206
[[-0.00248213]
 [-0.0018156 ]
 [-0.00311306]
 [-0.00354419]
 [ 0.00546426]
 [ 0.00011982]
 [-0.00175786]] [[-0.003]]
256 891
Round 732 acc= 0.712682379349046
[[-0.00248213]
 [-0.00146286]
 [-0.00583507]
 [-0.00106159]
 [ 0.00657058]
 [ 0.00221309]
 [-0.00049373]] [[-0.003]]
248 891
Round 733 acc= 0.7216610549943884
[[-0.00367887]
 [-0.00310206]
 [-0.00583507]
 [-0.00354419]
 [ 0.00532055]
 [ 0.00221309]
 [-0.00175786]] [[-0.003]]
241 891
Round 734 acc= 0.7295173961840629
[[-0.00165475]
 [-0.00230372]
 [-0.0035876 ]
 [-0.00029396]
 [ 0.00400181]
 [ 0.00147539]
 [-0.00243604]] [[

242 891
Round 782 acc= 0.7283950617283951
[[-0.00248213]
 [-0.00315893]
 [-0.00492773]
 [-0.00354419]
 [ 0.00564564]
 [ 0.00221309]
 [-0.00175786]] [[-0.003]]
258 891
Round 783 acc= 0.7104377104377104
[[-0.00128539]
 [-0.0016788 ]
 [-0.00583507]
 [-0.00106159]
 [ 0.0060834 ]
 [ 0.00221309]
 [-0.00049373]] [[-0.003]]
246 891
Round 784 acc= 0.7239057239057239
[[-0.00248213]
 [-0.00279236]
 [-0.00492773]
 [-0.00354419]
 [ 0.00522524]
 [ 0.00221309]
 [-0.00049373]] [[-0.003]]
233 891
Round 785 acc= 0.7384960718294051
[[-0.00045801]
 [-0.00216615]
 [-0.00268026]
 [-0.00153526]
 [ 0.00578793]
 [ 0.00147539]
 [-0.00243604]] [[-0.002]]
243 891
Round 786 acc= 0.7272727272727273
[[-0.00202412]
 [-0.00257819]
 [-0.00315481]
 [-0.00076763]
 [ 0.00665766]
 [ 0.0007377 ]
 [-0.00058595]] [[-0.001]]
245 891
Round 787 acc= 0.7250280583613917
[[-1.65475449e-03]
 [-3.11986041e-03]
 [-3.58760242e-03]
 [-4.01786673e-03]
 [ 6.31772152e-03]
 [ 1.47539026e-03]
 [ 9.22203856e-05]] [[-0.002]]
240 891
Round 788 

244 891
Round 841 acc= 0.7261503928170595
[[-0.00248213]
 [-0.00239581]
 [-0.00492773]
 [-0.00354419]
 [ 0.00501256]
 [ 0.00221309]
 [-0.00175786]] [[-0.003]]
251 891
Round 842 acc= 0.7182940516273849
[[-0.00165475]
 [-0.00292312]
 [-0.00540228]
 [-0.00029396]
 [ 0.0055218 ]
 [ 0.00147539]
 [-0.00243604]] [[-0.002]]
242 891
Round 843 acc= 0.7283950617283951
[[-0.0028515 ]
 [-0.00431872]
 [-0.0035876 ]
 [-0.00401787]
 [ 0.00649632]
 [ 0.00147539]
 [-0.00117191]] [[-0.002]]
244 891
Round 844 acc= 0.7261503928170595
[[-0.00165475]
 [-0.00237134]
 [-0.00449494]
 [-0.00401787]
 [ 0.0047295 ]
 [ 0.00147539]
 [-0.00117191]] [[-0.002]]
247 891
Round 845 acc= 0.7227833894500562
[[-0.00202412]
 [-0.00257819]
 [-0.00587682]
 [-0.00076763]
 [ 0.00699247]
 [ 0.00283096]
 [-0.00185008]] [[-0.001]]
255 891
Round 846 acc= 0.7138047138047138
[[-0.0028515 ]
 [-0.00242821]
 [-0.0035876 ]
 [-0.00401787]
 [ 0.00534336]
 [ 0.00147539]
 [-0.00117191]] [[-0.002]]
255 891
Round 847 acc= 0.7138047138047138
[[-0

252 891
Round 897 acc= 0.7171717171717171
[[-0.00248213]
 [-0.00177948]
 [-0.00583507]
 [-0.00354419]
 [ 0.00669205]
 [ 0.00221309]
 [-0.00175786]] [[-0.003]]
253 891
Round 898 acc= 0.7160493827160493
[[-4.58012403e-04]
 [-2.06932305e-03]
 [-3.58760242e-03]
 [-4.01786673e-03]
 [ 5.78515099e-03]
 [ 1.47539026e-03]
 [ 9.22203856e-05]] [[-0.002]]
251 891
Round 899 acc= 0.7182940516273849
[[-0.00248213]
 [-0.00296297]
 [-0.00492773]
 [-0.00354419]
 [ 0.0059339 ]
 [ 0.00221309]
 [-0.00049373]] [[-0.003]]
245 891
Round 900 acc= 0.7250280583613917
[[-1.65475449e-03]
 [-1.85644899e-03]
 [-4.49494098e-03]
 [-4.01786673e-03]
 [ 5.66089984e-03]
 [ 1.47539026e-03]
 [ 9.22203856e-05]] [[-0.002]]
239 891
Round 901 acc= 0.7317620650953984
[[-0.00082738]
 [-0.00087827]
 [-0.00134013]
 [-0.00325024]
 [ 0.00329314]
 [ 0.0007377 ]
 [-0.00058595]] [[-0.001]]
250 891
Round 902 acc= 0.7194163860830527
[[-0.00248213]
 [-0.00296758]
 [-0.00583507]
 [-0.00106159]
 [ 0.00644749]
 [ 0.00221309]
 [-0.00302199]] [

237 891
Round 955 acc= 0.734006734006734
[[-0.00367887]
 [-0.00196161]
 [-0.00492773]
 [-0.00354419]
 [ 0.00480515]
 [ 0.00011982]
 [-0.00175786]] [[-0.003]]
258 891
Round 956 acc= 0.7104377104377104
[[-0.00248213]
 [-0.00255028]
 [-0.0040204 ]
 [-0.00354419]
 [ 0.00475968]
 [ 0.00221309]
 [-0.00175786]] [[-0.003]]
245 891
Round 957 acc= 0.7250280583613917
[[-0.0028515 ]
 [-0.00311602]
 [-0.00540228]
 [-0.00153526]
 [ 0.00580895]
 [ 0.00147539]
 [-0.00243604]] [[-0.002]]
256 891
Round 958 acc= 0.712682379349046
[[-0.0028515 ]
 [-0.00357712]
 [-0.0035876 ]
 [-0.00401787]
 [ 0.00667902]
 [ 0.00147539]
 [-0.00117191]] [[-0.002]]
255 891
Round 959 acc= 0.7138047138047138
[[-0.00248213]
 [-0.00245345]
 [-0.00583507]
 [-0.00354419]
 [ 0.00556641]
 [ 0.00221309]
 [-0.00175786]] [[-0.003]]
245 891
Round 960 acc= 0.7250280583613917
[[-0.00165475]
 [-0.00165433]
 [-0.0035876 ]
 [-0.00401787]
 [ 0.00289563]
 [ 0.00147539]
 [-0.00117191]] [[-0.002]]
250 891
Round 961 acc= 0.7194163860830527
[[-0.0

In [136]:
w

array([[-0.00101945],
       [ 0.00075547],
       [-0.00103259],
       [ 0.00336448],
       [-0.00054163],
       [ 0.00185364],
       [-0.00154079]])

In [125]:
b

matrix([[153.865]])

In [105]:
y=w.T[1]
y

matrix([[2]])

In [108]:
np.multiply(y,w.T)

matrix([[ 2],
        [ 4],
        [ 6],
        [ 8],
        [10],
        [12],
        [14]])

In [177]:
def test(fileName,w,b):
    # 对data——test进行一样的预处理

    data_test = pd.read_csv(fileName)

    ans = data_test['Embarked'].value_counts()

    # 返回最大值索引
    fillstr = ans.idxmax()

    data_test['Embarked'] = data_test['Embarked'].fillna(fillstr)
    data_test.info()
    data_test.loc[data_test["Sex"] == "male", "Sex"] = 0
    data_test.loc[data_test["Sex"] == "female", "Sex"] = 1

    data_test.loc[data_test['Embarked'] == 'C', 'Embarked'] = 0
    data_test.loc[data_test['Embarked'] == 'Q', 'Embarked'] = 1
    data_test.loc[data_test['Embarked'] == 'S', 'Embarked'] = 2

    data_test['Age'] = data_test['Age'].fillna(data_test['Age'].median())
    mid = data_test['Fare'].median()
    data_test['Fare'] = data_test['Fare'].fillna(value=mid)

    feature = ["Pclass", "Age", "SibSp", "Parch", "Fare", "Sex", "Embarked", ]
    x_test=np.mat(data_test[feature])

    test_predictions = x_test@w+b
    test_predictions[test_predictions >= 0.5] = 1
    test_predictions[test_predictions < 0.5] = 0
    print(type(test_predictions))
    test_predictions=np.array(test_predictions.T)
    test_predictions=test_predictions.flatten()
    print(type(test_predictions))
    print(test_predictions)


    result = pd.DataFrame({'PassengerId':data_test['PassengerId'].as_matrix(), 'Survived':test_predictions.T.astype(np.int32)})


In [178]:

x_train,y_label=loadData('Titanic_data/train.csv')
x_norm=norm(x_train)
w,b=preceptron(x_norm,y_label)
test('Titanic_data/test.csv',w,b)

/Users/lihaoran/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:190: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)


232 891
Round 0 acc= 0.7396184062850729
[[-0.04580124]
 [-0.19033274]
 [-0.26802639]
 [-0.15352598]
 [ 0.51463418]
 [ 0.14753903]
 [-0.2436037 ]] [[-0.2]]
252 891
Round 1 acc= 0.7171717171717171
[[-0.16547545]
 [-0.27102507]
 [-0.54022795]
 [-0.02939563]
 [ 0.53343494]
 [ 0.14753903]
 [-0.2436037 ]] [[-0.2]]
252 891
Round 2 acc= 0.7171717171717171
[[-0.28514966]
 [-0.26971863]
 [-0.54022795]
 [-0.40178667]
 [ 0.60233725]
 [ 0.14753903]
 [-0.11719083]] [[-0.2]]
256 891
Round 3 acc= 0.712682379349046
[[-0.28514966]
 [-0.27863321]
 [-0.4494941 ]
 [-0.27765632]
 [ 0.56734518]
 [ 0.14753903]
 [-0.11719083]] [[-0.2]]
252 891
Round 4 acc= 0.7171717171717171
[[-0.16547545]
 [-0.16458804]
 [-0.54022795]
 [-0.40178667]
 [ 0.60927567]
 [ 0.14753903]
 [-0.11719083]] [[-0.2]]
239 891
Round 5 acc= 0.7317620650953984
[[-0.24821317]
 [-0.14705412]
 [-0.49277343]
 [-0.35441931]
 [ 0.44115084]
 [ 0.22130854]
 [-0.17578624]] [[-0.3]]
249 891
Round 6 acc= 0.7205387205387206
[[-0.28514966]
 [-0.22668271]
 

/Users/lihaoran/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:37: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.


In [170]:
test_predictions

NameError: name 'test_predictions' is not defined

In [16]:
data=pd.read_csv('mnist_train.csv',header=None)

In [17]:
data[0:30]

0    1    2    3    4    5    6    7    8    9    ...  775  776  777  778  \
0     5    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
1     0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
2     4    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
3     1    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
4     9    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
5     2    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
6     1    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
7     3    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
8     1    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
9     4    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
10    3    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
11    5    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
12    3    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
13    6    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
14    1    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
15    7    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
16    2    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
17    8    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
18    6    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
19    9    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
20    4    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
21    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
22    9    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
23    1    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
24    1    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
25    2    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
26    4    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
27    3    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
28    2    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
29    7    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   

    779  780  781  782  783  784  
0     0    0    0    0    0    0  
1     0    0    0    0    0    0  
2     0    0    0    0    0    0  
3     0    0    0    0    0    0  
4     0    0    0    0    0    0  
5     0    0    0    0    0    0  
6     0    0    0    0    0    0  
7     0    0    0    0    0    0  
8     0    0    0    0    0    0  
9     0    0    0    0    0    0  
10    0    0    0    0    0    0  
11    0    0    0    0    0    0  
12    0    0    0    0    0    0  
13    0    0    0    0    0    0  
14    0    0    0    0    0    0  
15    0    0    0    0    0    0  
16    0    0    0    0    0    0  
17    0    0    0    0    0    0  
18    0    0    0    0    0    0  
19    0    0    0    0    0    0  
20    0    0    0    0    0    0  
21    0    0    0    0    0    0  
22    0    0    0    0    0    0  
23    0    0    0    0    0    0  
24    0    0    0    0    0    0  
25    0    0    0    0    0    0  
26    0    0    0    0    0    0  
27    0    0    0    0    0    0  
28    0    0    0    0    0    0  
29    0    0    0    0    0    0  

[30 rows x 785 columns]

In [18]:
data=data.values
y_label=data[:,0]
y_label[y_label<5]=-1
y_label[y_label>=5]=1


In [19]:
y_label[0:30]

array([ 1, -1, -1, -1,  1, -1, -1, -1, -1, -1, -1,  1, -1,  1, -1,  1, -1,
        1,  1,  1, -1, -1,  1, -1, -1, -1, -1, -1, -1,  1])

In [14]:
len(y_label)

60000

In [20]:
a=np.mat([[1],[-1],[1]])

In [21]:
a

matrix([[ 1],
        [-1],
        [ 1]])

In [27]:
a[1,0]

-1

In [23]:
a[2]

matrix([[1]])

In [24]:
b=np.mat([[1],[-1],[-1]])

In [25]:
b

matrix([[ 1],
        [-1],
        [-1]])

In [26]:
a[1,]==b[1]

matrix([[ True]])

In [29]:
1.0==1

True